### ISSUE TITLE
"JointBERT" vs. "BertForMaskedLM" in model config json file

### ISSUE THREAD

**Issue by haomiao-li** [monologg/JointBERT#3]
Hi,

This is a great repo! I was using your code to train Bert on my own data, but I noticed that the architecture field in the model config json file changed. The code and data are exactly the same, but the architecture changed which is wired. 

Please see the attached screenshots. 
Do you know why this changed over time?
Thanks!

![Screen Shot 2020-02-17 at 5 16 17 PM](https://user-images.githubusercontent.com/46943237/74695590-570cc900-51a9-11ea-901c-a61432198a49.png)
![Screen Shot 2020-02-17 at 5 16 09 PM](https://user-images.githubusercontent.com/46943237/74695594-5aa05000-51a9-11ea-97a8-cf2bef788e80.png)

**Comment by pttzty** [comment]
@monologg Same problem for me

**Comment by monologg** [comment]
Hi!

@haomiao-li  Can you tell me the version of transformers library that you used? When I'm tried to reproduce this one, my config.json shows `JointBert` on `architectures` attributes.

------------
[Reproducing steps]

0. transformers==2.4.1

1. Create the dataset with the task name of `wow`

2. Add task name on processors dict (in data_loader.py)

![image](https://user-images.githubusercontent.com/28896432/74700784-fd0f1080-5247-11ea-9571-256a0f0d3234.png)

3. Then run the code as follow.

```bash
$ python main.py --task wow --model_type bert --model_dir wow_model --do_train
```

**Comment by monologg** [comment]
By the way, when I was making this repo, the version of `transformers` library was low, and the `architectures` attributes wasn't in the config.json:(

**Comment by monologg** [comment]
It seems like that the older version of `transformers` library has the bug. When I tried with the version under 2.4, the `architectures` is saved as `BertForMaskedLM` as default. But with new version (2.4.1), the `architectures` is correctly saved as `JointBert`.

@haomiao-li  @pttzty Can you try with `transformers` version of 2.4.1?

**Comment by haomiao-li** [comment]
@monologg Will try it asap. The error looks weird because the performance for the intent detection part did drop significantly with Bert Masked LM

**Comment by monologg** [comment]
> @monologg Will try it asap. The error looks weird because the performance for the intent detection part did drop significantly with Bert Masked LM

I've just checked this one. But even with ver 2.2.2 (config is also saved as `BertForMaskedLM`), the performance looks same. Below is the steps that I've tried. If my step is different with yours,  just let me know the steps you tried:)

-----------
[Reproducing steps]
0. transformers==2.2.2

1. In `main.py`, change the code to evaluate the dev set when `--do_eval`
(I've change the code to load all three dataset at the beginning)
![image](https://user-images.githubusercontent.com/28896432/74703695-57609f00-5251-11ea-9bf1-ac97da78cdbf.png)

2. Run the code
```bash
$ python main.py --task atis --model_dir atis_model --do_train --do_eval --num_train_epochs 1
```
3. Check the difference between the acc shown during training and the acc shown during evaluation

**Comment by haomiao-li** [comment]
@monologg Problem fixed after we upgraded to the latest version of the transformers. Thanks!
Just another side note that I think you were trying to use ignore_index to exclude pads from the loss function and the final predicted output, and it actually worked well for the two sample datasets. However in my case I was getting lots of "PAD" for the final prediction results where it should actually be "O" category, and I think the pad was actually not excluded.

**Comment by monologg** [comment]
> @monologg Problem fixed after we upgraded to the latest version of the transformers. Thanks!
> Just another side note that I think you were trying to use ignore_index to exclude pads from the loss function and the final predicted output, and it actually worked well for the two sample datasets. However in my case I was getting lots of "PAD" for the final prediction results where it should actually be "O" category, and I think the pad was actually not excluded.

Great! Thank you for reporting the bug:) I'll close this issue.
