### ISSUE TITLE
whether the results in tables are run on dev set?

### ISSUE THREAD

**Issue by caoxu915683474** [monologg/JointBERT#9]
I run your models, but can not achieve your results on test set.

**Comment by monologg** [comment]
The result are based on **test set**. I've done the greedy search of hyperparameter, for example `random seed`, `lr_rate` to get the best result. The hyperparameter written in `main.py` might not guarantee you to get the best result.

**Comment by caoxu915683474** [comment]
Can you share your hyperparameter ?  Appreciate it!

**Comment by monologg** [comment]
> Can you share your hyperparameter ? Appreciate it!

Sadly, I don't have the hyperparameter that I used:( 

Is the difference of the result big? Maybe as I changed the architecture of the repo recently, and it could make the difference of the result.

**Comment by caoxu915683474** [comment]
yes, the difference of the result big.
On snips, I can only achieve 91%  on sentence acc, 96% on slot f1.

**Comment by caoxu915683474** [comment]
Use bert

**Comment by monologg** [comment]
> Can you share your hyperparameter ? Appreciate it!

As I remember, just changing the `seed` gives a big difference of the result.

I recommend you to refer [this paper](https://arxiv.org/abs/2002.06305?fbclid=IwAR1-wULE_1d3hY_ZTEnrD59qe08kFoira7TwhRT8vY_PfJsPaa4tGqPY5gY).

**Comment by monologg** [comment]
> yes, the difference of the result big.
> On snips, I can only achieve 91% on sentence acc, 96% on slot f1.

I'll check that one and let you know

**Comment by caoxu915683474** [comment]
Thanks for your help!

**Comment by monologg** [comment]
> yes, the difference of the result big.
> On snips, I can only achieve 91% on sentence acc, 96% on slot f1.

![KakaoTalk_20200429_221433842](https://user-images.githubusercontent.com/28896432/80602903-ace3d400-8a6a-11ea-8c04-f1af88d2faf9.png)

I've just changed the `seed` to 771 and run it. Above is the test result I got. I'm sorry that I forgot the exact hyperparameter that I used to get the best result, but by controlling some hyperparameter (e.g. seed, lr), you could get the better result.

**Comment by caoxu915683474** [comment]
Oh, thanks a lot. It seems that the selection of the random seed is the key. I will follow your work and try more !

**Comment by monologg** [comment]
Great:) I'll close this issue. Feel free to reopen if I haven't fully answered your questions.
